# Generated by Django 2.2 on 2021-01-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JiaoWuChu',
            fields=[
                ('title', models.CharField(default='', help_text='标题, primary_key', max_length=120, primary_key=True, serialize=False, verbose_name='标题')),
                ('time', models.DateField(help_text='教务处网站上的发布时间', verbose_name='发布时间')),
                ('url', models.CharField(default='', help_text='内容url', max_length=300, verbose_name='内容url')),
                ('abstract', models.TextField(help_text='摘要', null=True, verbose_name='摘要')),
            ],
            options={
                'verbose_name': '教务处内容',
                'verbose_name_plural': '教务处内容',
            },
        ),
    ]
