# Generated by Django 2.2 on 2021-01-31 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jiaowuchu', '0002_auto_20210130_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jiaowuchunews',
            name='abstract',
        ),
    ]
