# Generated by Django 2.2 on 2021-01-31 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiaowuchu', '0003_remove_jiaowuchunews_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiaowuchunews',
            name='pic_url',
            field=models.CharField(default='', help_text='快照url', max_length=300, verbose_name='快照url'),
        ),
    ]
