# Generated by Django 2.2 on 2021-03-12 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jiaowuchu', '0004_jiaowuchunews_pic_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jiaowuchunews',
            options={'verbose_name': '教务快讯', 'verbose_name_plural': '教务快讯'},
        ),
    ]
