# Generated by Django 2.2 on 2021-02-03 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_verifytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='verifyType',
            field=models.CharField(default='0', help_text='验证类型 0-未验证 1-教务系统验证 9-superuser', max_length=10, verbose_name='验证类型'),
        ),
    ]
