# Generated by Django 2.2 on 2021-02-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210203_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='verifyType',
            field=models.CharField(default='0', help_text='验证类型 0-未验证 1-教务系统验证 9-superuser x-黑名单用户', max_length=10, verbose_name='验证类型'),
        ),
    ]
