# Generated by Django 2.2 on 2021-02-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210206_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='academy',
            field=models.CharField(default='', help_text='学院名称', max_length=100, null=True, verbose_name='学院名称'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='realName',
            field=models.CharField(default='', help_text='教务系统的真实姓名', max_length=50, null=True, verbose_name='教务系统的真实姓名'),
        ),
    ]
