# Generated by Django 2.2 on 2021-03-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210221_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='realName',
            field=models.CharField(default='', help_text='教务系统的真实姓名', max_length=50, null=True, verbose_name='姓名'),
        ),
    ]
