# Generated by Django 2.2 on 2021-07-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210718_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='verifyType',
            field=models.CharField(choices=[('0', '未验证'), ('1', '教务系统验证'), ('2', '新绿验证'), ('9', '超级管理员'), ('x', '黑名单用户')], default='0', help_text='验证类型 0-未验证 1-教务系统验证 9-superuser x-黑名单用户 2-新绿验证', max_length=10, verbose_name='验证类型'),
        ),
    ]
