# Generated by Django 2.2 on 2021-07-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210718_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后活跃时间'),
        ),
    ]
