# Generated by Django 2.2 on 2021-07-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210718_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='acceptance_letter',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='录取通知书'),
        ),
    ]
