# Generated by Django 2.2 on 2021-07-22 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userprofile_acceptance_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ksh',
            field=models.CharField(blank=True, default='', help_text='考生号，新绿验证时填写', max_length=40, null=True, verbose_name='考生号'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sfzh',
            field=models.CharField(blank=True, default='', help_text='身份证号，新绿验证时填写', max_length=40, null=True, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='realName',
            field=models.CharField(default='', help_text='新绿期间为验证时输入的姓名， 通过教务验证后为教务系统的真实姓名', max_length=50, null=True, verbose_name='姓名'),
        ),
    ]
