# Generated by Django 2.2 on 2021-07-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210722_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openId', models.CharField(db_index=True, default='', help_text='用户的openid', max_length=80, verbose_name='用户的openid')),
                ('xh', models.CharField(db_index=True, default='', help_text='学号', max_length=30, null=True, verbose_name='学号')),
            ],
            options={
                'verbose_name': '黑名单',
                'verbose_name_plural': '黑名单',
            },
        ),
    ]
