"""
Django settings for pocket_bfu_miniprogram_be project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import datetime
from .config import *
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&bd6t277vt(*iw9r7k9wp6e_q6s3ksg_p)g9zr0bj@u_89#ooe'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = DEBUG

ALLOWED_HOSTS = ALLOWED_HOSTS


# Application definition

INSTALLED_APPS = [
    'simplepro',
    'simpleui',
    'import_export',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'apps.users',
    'apps.content',
    'apps.comment',
    'apps.operate',
    'apps.xiaoli',
    'apps.changyonglianjie',
    'apps.sunnyrun',
    'apps.chengji',
    'apps.kechengbiao',
    'apps.jiaowuchu',
    'apps.qiniuyun',
    'apps.ad',
    'apps.globalvar',
    'apps.behaviortracking',
    'apps.notice',
    'apps.rules'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # simplepro的中间件
    'simplepro.middlewares.SimpleMiddleware'
]


ROOT_URLCONF = 'pocket_bfu_miniprogram_be.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pocket_bfu_miniprogram_be.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': MYSQL_DB,
        'USER': MYSQL_USER,
        'PASSWORD': MYSQL_PWD,
        'HOST': MYSQL_HOST,
        'PORT': MYSQL_PORT,
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4'
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


AUTH_USER_MODEL = "users.UserProfile"

REST_FRAMEWORK = {
    # 'PAGE_SIZE': 5,
    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',

        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '30/minute',
        'user': '90/minute'
    },
    # 'DEFAULT_RENDERER_CLASSES': (
    #     'rest_framework.renderers.JSONRenderer',
    # )
}

JWT_AUTH = {
    'JWT_EXPIRATION_DELTA': datetime.timedelta(seconds=1200),
    'JWT_AUTH_HEADER_PREFIX': 'JWT',
}

AUTHENTICATION_BACKENDS = (
    'apps.users.views.JWTBackend',
    'django.contrib.auth.backends.ModelBackend',
)

# SimpleUI
SIMPLEUI_DEFAULT_THEME = 'green.css'
SIMPLEUI_ICON = {
    '内容管理': 'fas fa-comment-alt',
    '用户管理': 'fas fa-user-friends',
    '用户信息': 'far fa-user-circle',
    '帖子': 'far fa-comment-alt',
    '评论管理': 'fas fa-comments',
    '评论': 'far fa-comments',
    '教务新闻': 'fas fa-newspaper',
    '教务快讯': 'far fa-newspaper',
    '常用链接': 'fas fa-link',
    '校历': 'fas fa-calendar-day',
    '交互操作': 'fas fa-paw',
    '赞帖子': 'far fa-heart',
    '收藏帖子': 'far fa-star',
    '赞评论': 'far fa-thumbs-up',
    '行为追踪': 'fas fa-spider',
    '截屏事件': 'fas fa-tablet-alt',
    '全局变量': 'fas fa-meteor'
}
SIMPLEUI_CONFIG = {
    'system_keep': False,
    'menu_display': ['用户管理', '内容管理', '评论管理', '规则', '通知', '交互操作', '教务新闻', '常用链接', '校历', '全局变量',
                     '行为追踪',
                     '广告', '管理', '认证和授权'],      # 开启排序和过滤功能, 不填此字段为默认排序和全部显示, 空列表[] 为全部不显示.
}



APPID = APPID
APPSECRET = APPSECRET

# # redis
# REDIS_HOST = REDIS_HOST
# REDIS_PORT = REDIS_PORT
# REDIS_PWD = REDIS_PWD
# DB = DB

# CACHES = {
#     "default": {
#         "BACKEND": "django_redis.cache.RedisCache",
#         "LOCATION": "redis://:" + REDIS_PWD + "@" + REDIS_HOST + ":" + REDIS_PORT + "/1",
#         "OPTIONS": {
#             "CLIENT_CLASS": "django_redis.client.DefaultClient",
#         }
#     }
# }

REST_FRAMEWORK_EXTENSIONS = {
    'DEFAULT_CACHE_RESPONSE_TIMEOUT': 10,
}

"""
控制课程表，第一周的第一天
"""
FIRST_WEEK_FIRST_DAY = datetime.date(2021, 9, 6)
MAX_WEEK = 22
XNXQID = '2021-2022-1'  # 学年学期ID


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
print(STATIC_ROOT)

sentry_sdk.init(
    dsn="https://8e15243f7fe84b969cccc72e925c16b6@o547558.ingest.sentry.io/5669954",
    integrations=[DjangoIntegration()],
    traces_sample_rate=1.0,

    # If you wish to associate users to errors (assuming you are using
    # django.contrib.auth) you may enable sending PII data.
    send_default_pii=True
)
