# Generated by Django 2.2 on 2021-01-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XiaoLi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='图片标题', max_length=20, verbose_name='图片标题')),
                ('img', models.CharField(default='', help_text='图片url', max_length=200, verbose_name='图片url')),
                ('priority', models.IntegerField(default=0, help_text='优先级', verbose_name='优先级')),
            ],
            options={
                'verbose_name': '校历',
                'verbose_name_plural': '校历',
            },
        ),
    ]
