# Generated by Django 2.2 on 2021-02-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LikeToContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openId', models.CharField(db_index=True, help_text='点赞用户的id', max_length=80, verbose_name='点赞用户的id')),
                ('contentId', models.IntegerField(help_text='被点赞内容id', verbose_name='被点赞内容id')),
                ('createTime', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, help_text='最后修改时间', verbose_name='最后修改时间')),
            ],
            options={
                'verbose_name': '点赞-内容',
                'verbose_name_plural': '点赞-内容',
                'unique_together': {('openId', 'contentId')},
            },
        ),
        migrations.CreateModel(
            name='LikeToComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openId', models.CharField(db_index=True, help_text='点赞用户的id', max_length=80, verbose_name='点赞用户的id')),
                ('commentId', models.IntegerField(help_text='被点赞评论id', verbose_name='被点赞评论id')),
                ('createTime', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, help_text='最后修改时间', verbose_name='最后修改时间')),
            ],
            options={
                'verbose_name': '点赞-评论',
                'verbose_name_plural': '点赞-评论',
                'unique_together': {('openId', 'commentId')},
            },
        ),
        migrations.CreateModel(
            name='FavToContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openId', models.CharField(db_index=True, help_text='收藏用户的id', max_length=80, verbose_name='收藏用户的id')),
                ('contentId', models.IntegerField(help_text='被收藏内容id', verbose_name='被收藏内容id')),
                ('createTime', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, help_text='最后修改时间', verbose_name='最后修改时间')),
            ],
            options={
                'verbose_name': '收藏-内容',
                'verbose_name_plural': '收藏-内容',
                'unique_together': {('openId', 'contentId')},
            },
        ),
    ]
