# Generated by Django 2.2 on 2021-06-22 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operate', '0003_reporttocomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportToComment',
            new_name='ReportToContent',
        ),
    ]
