# Generated by Django 2.2 on 2021-06-22 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operate', '0004_auto_20210622_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporttocontent',
            options={'verbose_name': '举报内容', 'verbose_name_plural': '举报内容'},
        ),
    ]
