# Generated by Django 2.2 on 2021-06-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operate', '0005_auto_20210622_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttocontent',
            name='openId',
            field=models.CharField(db_index=True, help_text='举报用户的openId', max_length=80, verbose_name='举报用户的openId'),
        ),
    ]
