# Generated by Django 2.2 on 2021-05-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureScreenTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openId', models.CharField(db_index=True, default='', help_text='用户的openid', max_length=80, verbose_name='用户的openid')),
                ('pageUrl', models.TextField(blank=True, null=True, verbose_name='页面url')),
                ('createTime', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, help_text='最后修改时间', verbose_name='最后修改时间')),
            ],
            options={
                'verbose_name': '用户截屏事件',
                'verbose_name_plural': '用户截屏事件',
            },
        ),
    ]
