# Generated by Django 2.2 on 2021-10-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColdContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentId', models.IntegerField(db_index=True, help_text='冷帖子的id，只有评论或点赞、收藏过的用户能正常排名，对其它用户降权', null=True, verbose_name='冷帖子id')),
                ('page_number', models.IntegerField(default=10, help_text='表示把该帖子限制在分页的第几页', verbose_name='限制页数')),
            ],
            options={
                'verbose_name': '冷帖子',
                'verbose_name_plural': '冷帖子',
            },
        ),
        migrations.CreateModel(
            name='ColdUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xh', models.CharField(db_index=True, default='', help_text='冷用户的学号', max_length=30, null=True, verbose_name='冷用户的学号')),
                ('delta', models.IntegerField(default=-200, help_text='权重变量，降权为负数', null=True, verbose_name='权重变量')),
            ],
            options={
                'verbose_name': '冷用户',
                'verbose_name_plural': '冷用户',
            },
        ),
    ]
