# Generated by Django 2.2 on 2021-12-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text='包含关键词的帖子会被处理', max_length=100, verbose_name='屏蔽关键词')),
                ('content_state', models.CharField(choices=[('1', '正常'), ('0', '内容涉嫌违规，系统自动屏蔽'), ('3', '应相关方面要求，该内容已被删除'), ('4', '仅同班可见'), ('5', '仅同级同专业可见'), ('6', '仅同级同学院可见'), ('7', '仅作者自身可见')], default='1', help_text='控制内容显示状态，只有状态为正常的帖子可在列表中显示', max_length=5, verbose_name='帖子触发后状态')),
                ('comment_state', models.CharField(choices=[('1', '正常'), ('0', '内容涉嫌违规，系统自动屏蔽')], default='1', help_text='内容状态 1-正常，0-隐藏，2-冷却', max_length=5, verbose_name='评论触发后状态')),
                ('if_notice', models.BooleanField(default=False, help_text='触发后是否推送到飞书', verbose_name='提醒')),
                ('valid_time_to', models.DateTimeField(verbose_name='有效期至')),
                ('remark', models.TextField(verbose_name='备注')),
            ],
        ),
    ]
