# Generated by Django 2.2 on 2021-12-22 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0003_banwords_priority_delta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BanWords',
            new_name='KeyWords',
        ),
    ]
