# Generated by Django 2.2 on 2021-12-22 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0004_auto_20211222_0047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keywords',
            options={'verbose_name': '关键词策略', 'verbose_name_plural': '关键词策略'},
        ),
    ]
