# Generated by Django 2.2 on 2021-12-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0005_auto_20211222_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywords',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
