# Generated by Django 2.2 on 2021-07-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.FloatField(default=0.0, verbose_name='优先级')),
                ('component', models.CharField(choices=[('index', 'index')], default='index', help_text='指定具体的一个NoticeBar', max_length=50, verbose_name='组件')),
                ('content', models.TextField(default='', verbose_name='通知栏内容')),
                ('xh_startswith', models.CharField(blank=True, default='', help_text='__startwith', max_length=20, verbose_name='学号前缀')),
                ('color', models.CharField(default='#ed6a0c', help_text='文字颜色', max_length=20)),
                ('background', models.CharField(default='#fcefcf', help_text='背景色', max_length=20)),
                ('mode', models.CharField(choices=[('None', 'Nonde'), ('link', 'link')], default='None', help_text='link显示超链接箭头', max_length=20, verbose_name='模式')),
                ('to_type', models.CharField(choices=[('miniprogram', '小程序'), ('url', '网页url')], default='None', max_length=20, verbose_name='跳转类型')),
                ('to_url', models.TextField(blank=True, default='', help_text='跳转链接', null=True)),
                ('show', models.BooleanField(default=True, help_text='是否生效')),
                ('createTime', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
            },
        ),
    ]
