# Generated by Django 2.2 on 2021-07-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='delay',
            field=models.FloatField(default=0.5, verbose_name='动画延迟'),
        ),
        migrations.AddField(
            model_name='notice',
            name='left_icon',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='左侧图标'),
        ),
        migrations.AddField(
            model_name='notice',
            name='scrollable',
            field=models.BooleanField(default=True, verbose_name='是否滚动'),
        ),
        migrations.AddField(
            model_name='notice',
            name='speed',
            field=models.IntegerField(default=32, verbose_name='滚动速度'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='background',
            field=models.CharField(default='#fcefcf', max_length=20, verbose_name='背景色'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='color',
            field=models.CharField(default='#ed6a0c', max_length=20, verbose_name='文字颜色'),
        ),
    ]
