# Generated by Django 2.2 on 2021-07-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_auto_20210703_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='mode',
            field=models.CharField(choices=[('None', 'None'), ('link', 'link')], default='None', help_text='link显示超链接箭头', max_length=20, verbose_name='模式'),
        ),
    ]
