# Generated by Django 2.2 on 2021-07-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_auto_20210703_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='to_type',
            field=models.CharField(choices=[('None', '不跳转'), ('miniprogram', '小程序'), ('url', '网页url')], default='None', max_length=20, verbose_name='跳转类型'),
        ),
    ]
