# Generated by Django 2.2 on 2021-07-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_auto_20210703_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='component',
            field=models.CharField(default='index', help_text='指定具体的一个NoticeBar', max_length=50, verbose_name='组件'),
        ),
    ]
