# Generated by Django 2.2 on 2021-02-03 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openId', models.CharField(db_index=True, default='', help_text='作者的openId', max_length=80, verbose_name='作者的openId')),
                ('nLike', models.IntegerField(default=0, help_text='点赞数', verbose_name='点赞数')),
                ('nComment', models.IntegerField(default=0, help_text='评论数', verbose_name='评论数')),
                ('priority', models.FloatField(default=0.0, help_text='优先级', verbose_name='优先级')),
                ('state', models.CharField(default='1', help_text='内容状态 1-正常，0-隐藏，2-冷却', max_length=5, verbose_name='内容状态')),
                ('contentText', models.TextField(blank=True, default='', help_text='内容文字', verbose_name='内容文字')),
                ('contentImg', models.TextField(blank=True, default='', help_text='内容配图url, url1|url2|url3|...', null=True, verbose_name='内容配图url')),
                ('createTime', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, help_text='最后修改时间', verbose_name='最后修改时间')),
            ],
            options={
                'verbose_name': '内容管理',
                'verbose_name_plural': '内容管理',
            },
        ),
    ]
