# Generated by Django 2.2 on 2021-02-17 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': '内容', 'verbose_name_plural': '内容'},
        ),
    ]
