# Generated by Django 2.2 on 2021-03-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20210217_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': '帖子', 'verbose_name_plural': '帖子'},
        ),
        migrations.AddField(
            model_name='content',
            name='decoration_url',
            field=models.TextField(blank=True, default='', help_text='挂件url', null=True, verbose_name='挂件url'),
        ),
    ]
