# Generated by Django 2.2 on 2021-04-15 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20210312_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='setTop',
            field=models.BooleanField(default=False, help_text='是否置顶', verbose_name='是否置顶'),
        ),
    ]
