# Generated by Django 2.2 on 2021-04-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_content_settop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='setTop',
            field=models.BooleanField(blank=True, default=False, help_text='是否置顶', verbose_name='是否置顶'),
        ),
    ]
