# Generated by Django 2.2 on 2021-04-15 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20210415_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='setTop',
        ),
    ]
