# Generated by Django 2.2 on 2021-04-15 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_content_settop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='setTop',
        ),
    ]
