# Generated by Django 2.2 on 2021-04-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_content_settop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='setTop',
            field=models.IntegerField(default=0, help_text='是否置顶', verbose_name='是否置顶'),
        ),
    ]
