# Generated by Django 2.2 on 2021-04-15 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20210415_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='setTop',
        ),
    ]
