# Generated by Django 2.2 on 2021-04-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_remove_content_settop'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='setTop',
            field=models.IntegerField(blank=True, default=0, help_text='是否置顶', null=True, verbose_name='是否置顶'),
        ),
    ]
