# Generated by Django 2.2 on 2021-04-15 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_content_settop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='setTop',
            field=models.CharField(blank=True, default='0', help_text='是否置顶', max_length=5, null=True, verbose_name='是否置顶'),
        ),
    ]
