# Generated by Django 2.2 on 2021-04-15 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_auto_20210415_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='setTop',
            field=models.BooleanField(blank=True, default=False, help_text='是否置顶', null=True, verbose_name='是否置顶'),
        ),
    ]
