# Generated by Django 2.2 on 2021-04-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_auto_20210415_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='priority_delta',
            field=models.FloatField(default=0.0, help_text='优先级变量', verbose_name='优先级变量'),
        ),
    ]
