# Generated by Django 2.2 on 2021-06-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_auto_20210622_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='state',
            field=models.CharField(choices=[('1', '正常'), ('0', '内容涉嫌违规，系统自动屏蔽'), ('2', '该内容已被发布者删除'), ('3', '应相关方面要求，该内容已被删除')], default='1', help_text='控制内容显示状态，只有状态为正常的帖子可在列表中显示', max_length=5, verbose_name='内容状态'),
        ),
    ]
