# Generated by Django 2.2 on 2021-07-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_auto_20210624_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPriorityRuleForOpenId',
            fields=[
                ('openId', models.CharField(db_index=True, default='', help_text='作者的openId', max_length=80, primary_key=True, serialize=False, verbose_name='作者的openId')),
                ('priority_delta', models.FloatField(default=0.0, help_text='初始化优先级变量', verbose_name='优先级变量')),
            ],
            options={
                'verbose_name': '优先级初始化规则(基于openId)',
                'verbose_name_plural': '优先级初始化规则(基于openId)',
            },
        ),
        migrations.CreateModel(
            name='ContentPriorityRuleForXh',
            fields=[
                ('xh', models.CharField(db_index=True, default='', help_text='学号', max_length=30, primary_key=True, serialize=False, verbose_name='学号')),
                ('priority_delta', models.FloatField(default=0.0, help_text='初始化优先级变量', verbose_name='初始化优先级变量')),
            ],
            options={
                'verbose_name': '优先级初始化规则(基于学号)',
                'verbose_name_plural': '优先级初始化规则(基于学号)',
            },
        ),
    ]
