# Generated by Django 2.2 on 2021-12-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_auto_20211027_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='state',
            field=models.CharField(choices=[('1', '正常'), ('0', '内容涉嫌违规，系统自动屏蔽'), ('3', '应相关方面要求，该内容已被删除'), ('4', '仅同班可见'), ('5', '仅同级同专业可见'), ('6', '仅同级同学院可见'), ('7', '仅作者自身可见')], default='1', help_text='控制内容显示状态，只有状态为正常的帖子可在列表中显示', max_length=5, verbose_name='内容状态'),
        ),
    ]
