# Generated by Django 2.2 on 2021-02-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openId', models.CharField(db_index=True, default='', help_text='作者的openId', max_length=80, verbose_name='作者的openId')),
                ('commentText', models.TextField(blank=True, default='', help_text='内容文字', verbose_name='内容文字')),
                ('nLike', models.IntegerField(default=0, help_text='点赞数', verbose_name='点赞数')),
                ('deep', models.IntegerField(default=1, help_text='评论级数 1-一级评论，2-二级评论', verbose_name='评论级数')),
                ('reply', models.IntegerField(help_text='回复的commentId,仅对二级评论生效', null=True, verbose_name='回复的commentId')),
                ('contentId', models.IntegerField(help_text='评论及回复所属的内容的id', verbose_name='所属的内容id')),
                ('state', models.CharField(default='1', help_text='内容状态 1-正常，0-隐藏，2-冷却', max_length=5, verbose_name='内容状态')),
                ('createTime', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, help_text='最后修改时间', verbose_name='最后修改时间')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
    ]
