# Generated by Django 2.2 on 2021-02-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.IntegerField(default=-1, help_text='回复的commentId,仅对二级评论生效', null=True, verbose_name='回复的commentId'),
        ),
    ]
