# Generated by Django 2.2 on 2021-02-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20210217_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='contentId',
            field=models.IntegerField(db_index=True, help_text='评论及回复所属的内容的id', verbose_name='所属的内容id'),
        ),
    ]
