# Generated by Django 2.2 on 2021-02-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20210217_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentId',
            field=models.IntegerField(db_index=True, default=-1, help_text='二级评论所属的一级评论的id', verbose_name='二级评论所属的一级评论的id'),
        ),
    ]
