# Generated by Django 2.2 on 2021-03-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_comment_commentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentId',
            field=models.IntegerField(db_index=True, default=-1, help_text='二级评论所属的一级评论的id', verbose_name='父评论的id'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='contentId',
            field=models.IntegerField(db_index=True, help_text='评论及回复所属的内容的id', verbose_name='所属的帖子id'),
        ),
    ]
