# Generated by Django 2.2 on 2021-12-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_auto_20210312_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='state',
            field=models.CharField(choices=[('1', '正常'), ('0', '内容涉嫌违规，系统自动屏蔽')], default='1', help_text='内容状态 1-正常，0-隐藏，2-冷却', max_length=5, verbose_name='内容状态'),
        ),
    ]
