# Generated by Django 2.2 on 2021-05-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalVar',
            fields=[
                ('key', models.CharField(default='', max_length=100, primary_key=True, serialize=False, verbose_name='键')),
                ('value', models.TextField(default='', help_text='广告配图', verbose_name='广告配图')),
                ('help_text', models.TextField(blank=True, default='', help_text='广告配图', verbose_name='广告配图')),
                ('createTime', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, help_text='最后修改时间', verbose_name='最后修改时间')),
            ],
            options={
                'verbose_name': '全局变量',
                'verbose_name_plural': '全局变量',
            },
        ),
    ]
