# Generated by Django 2.2 on 2021-05-01 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalvar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalvar',
            name='value',
            field=models.TextField(default='', verbose_name='值'),
        ),
    ]
