# Generated by Django 2.2 on 2021-05-01 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalvar', '0002_auto_20210501_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalvar',
            name='help_text',
            field=models.TextField(blank=True, default='', help_text='备注', verbose_name='备注'),
        ),
    ]
