# Generated by Django 2.2 on 2021-01-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangYongLianJie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='网站名称', max_length=20, verbose_name='网站名称')),
                ('desc', models.CharField(default='', help_text='网站描述', max_length=30, verbose_name='网站描述')),
                ('url', models.CharField(default='', help_text='网站url', max_length=200, verbose_name='网站url')),
                ('priority', models.IntegerField(default=0, help_text='优先级', verbose_name='优先级')),
            ],
            options={
                'verbose_name': '常用链接',
                'verbose_name_plural': '常用链接',
            },
        ),
    ]
