# Generated by Django 2.2 on 2021-04-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultAD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_text', models.CharField(default='', help_text='广告文案', max_length=60, verbose_name='广告文案')),
                ('ad_img', models.TextField(default='', help_text='广告配图', verbose_name='广告配图')),
                ('tag_a_text', models.CharField(default='', help_text='tagA文字', max_length=15, null=True, verbose_name='tagA文字')),
                ('tag_a_color', models.CharField(default='#f85c23', help_text='tagA颜色', max_length=15, null=True, verbose_name='tagA颜色')),
                ('tag_b_text', models.CharField(default='', help_text='tagB文字', max_length=15, null=True, verbose_name='tagB文字')),
                ('tag_b_color', models.CharField(default='#f85c23', help_text='tagB颜色', max_length=15, null=True, verbose_name='tagB颜色')),
                ('button_text', models.CharField(default='', max_length=20, null=True, verbose_name='引导按键文字')),
                ('button_color', models.CharField(default='#5abe64', help_text='引导按键颜色', max_length=15, null=True, verbose_name='引导按键颜色')),
                ('type', models.CharField(default='0', help_text='0：淘宝客  1：小程序', max_length=10, verbose_name='广告类型')),
                ('additional_field_a', models.TextField(default='', help_text='附加字段A', verbose_name='附加字段A')),
                ('additional_field_b', models.TextField(default='', help_text='附加字段B', verbose_name='附加字段B')),
                ('valid_time', models.DateField(help_text='广告在此期限前生效', verbose_name='有效时间至')),
                ('createTime', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, help_text='最后修改时间', verbose_name='最后修改时间')),
            ],
        ),
    ]
