# Generated by Django 2.2 on 2021-04-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaultad',
            options={'verbose_name': '广告', 'verbose_name_plural': '广告'},
        ),
        migrations.AddField(
            model_name='defaultad',
            name='feature_sex',
            field=models.CharField(default='all', help_text='广告能被该性别用户看到 all：全部 1：男性 0：女性', max_length=20, null=True, verbose_name='广告能被该性别用户看到'),
        ),
        migrations.CreateModel(
            name='ADLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.IntegerField(help_text='广告id', verbose_name='广告id')),
                ('openId', models.CharField(db_index=True, default='', help_text='用户的openid', max_length=80, verbose_name='用户的openid')),
                ('createTime', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, help_text='最后修改时间', verbose_name='最后修改时间')),
            ],
            options={
                'verbose_name': '广告推送日志',
                'verbose_name_plural': '广告推送日志',
                'unique_together': {('ad_id', 'openId')},
            },
        ),
    ]
