# Generated by Django 2.2 on 2021-04-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_auto_20210420_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultad',
            name='rate',
            field=models.CharField(default='1/1000', help_text='频率限制，如60/10为60秒内显示不超过10次', max_length=50, verbose_name='频率限制'),
        ),
    ]
