# Generated by Django 2.2 on 2021-04-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0003_defaultad_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultad',
            name='valid_time',
            field=models.DateTimeField(help_text='广告在此期限前生效', verbose_name='有效时间至'),
        ),
    ]
