# Generated by Django 2.2 on 2021-04-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0004_auto_20210421_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultad',
            name='additional_field_a',
            field=models.TextField(blank=True, default='', help_text='附加字段A', null=True, verbose_name='附加字段A'),
        ),
        migrations.AlterField(
            model_name='defaultad',
            name='additional_field_b',
            field=models.TextField(blank=True, default='', help_text='附加字段B', null=True, verbose_name='附加字段B'),
        ),
    ]
