# Generated by Django 2.2 on 2021-04-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0005_auto_20210421_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultad',
            name='feature_sex',
            field=models.CharField(choices=[('all', '性别不限'), ('male', '男'), ('female', '女')], default='all', help_text='广告能被该性别用户看到 all：全部 male：男性 female：女性', max_length=20, null=True, verbose_name='广告能被该性别用户看到'),
        ),
        migrations.AlterField(
            model_name='defaultad',
            name='type',
            field=models.CharField(choices=[('0', '复制淘口令'), ('1', '跳转小程序')], default='0', help_text='0：复制淘口令  1：跳转小程序', max_length=10, verbose_name='广告类型'),
        ),
    ]
