# Generated by Django 2.2 on 2021-04-22 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0006_auto_20210422_2139'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adlog',
            unique_together=set(),
        ),
    ]
