# Generated by Django 2.2 on 2021-05-05 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0007_auto_20210422_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultad',
            name='button_color',
            field=models.CharField(blank=True, default='#5abe64', help_text='引导按键颜色', max_length=15, null=True, verbose_name='引导按键颜色'),
        ),
        migrations.AlterField(
            model_name='defaultad',
            name='button_text',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='引导按键文字'),
        ),
        migrations.AlterField(
            model_name='defaultad',
            name='tag_a_color',
            field=models.CharField(blank=True, default='#f85c23', help_text='tagA颜色', max_length=15, null=True, verbose_name='tagA颜色'),
        ),
        migrations.AlterField(
            model_name='defaultad',
            name='tag_a_text',
            field=models.CharField(blank=True, default='', help_text='tagA文字', max_length=15, null=True, verbose_name='tagA文字'),
        ),
        migrations.AlterField(
            model_name='defaultad',
            name='tag_b_color',
            field=models.CharField(blank=True, default='#f85c23', help_text='tagB颜色', max_length=15, null=True, verbose_name='tagB颜色'),
        ),
        migrations.AlterField(
            model_name='defaultad',
            name='tag_b_text',
            field=models.CharField(blank=True, default='', help_text='tagB文字', max_length=15, null=True, verbose_name='tagB文字'),
        ),
    ]
